default: &default
  adapter: postgresql
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode

development:
  <<: *default
  database: maine_app_dev
  username: postgres
  password: password

test:
  <<: *default
  database: maine_app_test
  username: postgres
  password: password

production:
  <<: *default
  database: maine_app_production
